Repository entando/entando-cms, pull requests merged in 2020-05, with the labels that each got.

#151 ENG-389 use token
  .npmrc
  commands/publish.js
Labels: size/XS

#153 ENG-389 remove npmrc
  .npmrc
  jenkins-x.yml
Labels: size/XS

#154 ENG-389 reset version
  .npmrc
  jenkins-x.yml
  package-lock.json
  package.json
Labels: size/M

#155 ENG-389 use env variable as a secret
  .npmrc
  jenkins-x.yml
Labels: size/XS

#157 ENG-444 re-design image add/edit from FE
  src/state/assets/__tests__/actions.test.js
  src/state/assets/actions.js
Labels: approved, size/S

#156 ENG-443 fix broken cms content widget edit
  src/ui/widget-forms/ContentsQueryConfigContainer.js
  src/ui/widget-forms/MultipleContentsConfigContainer.js
  src/ui/widget-forms/SingleContentConfigContainer.js
Labels: approved, size/M

#158 ENG-478 languages support on CMS content editing
  src/ui/common/form/RenderRichTextEditor.js
  src/ui/common/rich-text-editor/RichTextEditor.js
  src/ui/edit-content/content-attributes/AttributeField.js
  src/ui/edit-content/content-attributes/ContentAttributes.js
  src/ui/edit-content/content-attributes/__tests__/ContentAttributes.test.js
Labels: approved, size/M

#159 ENG-480 remove charts folder
  charts/entando-cms/.helmignore
  charts/entando-cms/Chart.yaml
  charts/entando-cms/Makefile
  charts/entando-cms/README.md
  charts/entando-cms/templates/NOTES.txt
  charts/entando-cms/templates/_helpers.tpl
  charts/entando-cms/templates/canary.yaml
  charts/entando-cms/templates/deployment.yaml
  charts/entando-cms/templates/hpa.yaml
  charts/entando-cms/templates/ingress.yaml
  charts/entando-cms/templates/ksvc.yaml
  charts/entando-cms/templates/service.yaml
  charts/entando-cms/values.yaml
  charts/preview/Chart.yaml
  charts/preview/Makefile
  charts/preview/requirements.yaml
  charts/preview/values.yaml
  package-lock.json
Labels: size/XL

#160 ENG-480 remove charts
  charts/javascript/.helmignore
  charts/javascript/Chart.yaml
  charts/javascript/Makefile
  charts/javascript/README.md
  charts/javascript/templates/NOTES.txt
  charts/javascript/templates/_helpers.tpl
  charts/javascript/templates/canary.yaml
  charts/javascript/templates/deployment.yaml
  charts/javascript/templates/hpa.yaml
  charts/javascript/templates/ingress.yaml
  charts/javascript/templates/ksvc.yaml
  charts/javascript/templates/service.yaml
  charts/javascript/values.yaml
Labels: size/L

#161 ENG-480 remove charts again
  charts/entando-cms/.helmignore
  charts/entando-cms/Chart.yaml
  charts/entando-cms/Makefile
  charts/entando-cms/README.md
  charts/entando-cms/templates/NOTES.txt
  charts/entando-cms/templates/_helpers.tpl
  charts/entando-cms/templates/canary.yaml
  charts/entando-cms/templates/deployment.yaml
  charts/entando-cms/templates/hpa.yaml
  charts/entando-cms/templates/ingress.yaml
  charts/entando-cms/templates/ksvc.yaml
  charts/entando-cms/templates/service.yaml
  charts/entando-cms/values.yaml
  charts/preview/Chart.yaml
  charts/preview/Makefile
  charts/preview/requirements.yaml
  charts/preview/values.yaml
Labels: size/XL

#162 ENG-480 remove charts
  charts/entando-cms/.helmignore
  charts/entando-cms/Chart.yaml
  charts/entando-cms/Makefile
  charts/entando-cms/README.md
  charts/entando-cms/templates/NOTES.txt
  charts/entando-cms/templates/_helpers.tpl
  charts/entando-cms/templates/canary.yaml
  charts/entando-cms/templates/deployment.yaml
  charts/entando-cms/templates/hpa.yaml
  charts/entando-cms/templates/ingress.yaml
  charts/entando-cms/templates/ksvc.yaml
  charts/entando-cms/templates/service.yaml
  charts/entando-cms/values.yaml
  charts/preview/Chart.yaml
  charts/preview/Makefile
  charts/preview/requirements.yaml
  charts/preview/values.yaml
Labels: size/XL

#163 ENG-480 update publish script
  commands/publish.js
Labels: size/XS

#165 ENG-480 test regex change
  commands/publish.js
Labels: size/XS

#166 ENG-480 test regex change
  jenkins-x.yml
  package.json
Labels: size/XS

#167 ENG-480 package regex
  package-lock.json
  package.json
Labels: size/S

#164 ENG-527: fixes default content model list field name
  src/ui/content-type/AddContentTypeForm.js
Labels: approved, size/XS

#168 ENG-480 package regex
  src/ui/edit-content/EditContentFormContainer.js
Labels: size/XS

#136 ENG-384 Add validation for link attribute
  src/helpers/__tests__/attrValidation.test.js
  src/helpers/attrValidation.js
  src/ui/edit-content/content-attributes/AttributeField.js
Labels: approved, size/M

#169 ENG-502 List/Monolist dates fix
  src/state/edit-content/__tests__/actions.test.js
  src/state/edit-content/actions.js
Labels: approved, size/L

#170 ENG-492 implement user list for content filtering
  src/api/__tests__/users.test.js
  src/api/users.js
  src/sass/contents/ContentsFilter.scss
  src/state/__tests__/rootReducer.test.js
  src/state/rootReducer.js
  src/state/users/__tests__/actions.test.js
  src/state/users/__tests__/reducer.test.js
  src/state/users/__tests__/selectors.test.js
  src/state/users/actions.js
  src/state/users/reducer.js
  src/state/users/selectors.js
  src/state/users/types.js
  src/testutils/mocks/users.js
  src/ui/contents/Contents.js
  src/ui/contents/ContentsContainer.js
  src/ui/contents/ContentsFilter.js
Labels: approved, size/L

#171 Change clear error ordering
  src/state/assets/__tests__/actions.test.js
  src/state/assets/actions.js
  src/state/content-settings/__tests__/actions.test.js
  src/state/content-settings/actions.js
  src/state/content-template/__tests__/actions.test.js
  src/state/content-template/actions.js
  src/state/content-type/__tests__/actions.test.js
  src/state/content-type/actions.js
  src/state/contents/__tests__/actions.test.js
  src/state/contents/actions.js
  src/state/edit-content/actions.js
  src/state/page-config/__tests__/actions.test.js
  src/state/page-config/actions.js
Labels: size/M

#173 ENG-550 dnd bug
  package-lock.json
  src/sass/assets/AssetsAdvancedFilter.scss
  src/sass/assets/AssetsList.scss
  src/sass/assets/UploadAsset.scss
  src/ui/assets/AssetsUpload.js
  src/ui/common/form/RenderDatePickerInput.js
Labels: approved, size/M

#174 ENG-550 test change for jx
  src/ui/contents/Contents.js
Labels: approved, size/XS

#172 ENG-519 implement cms side for expand/collapse all
  package-lock.json
  package.json
  src/state/pages/__tests__/actions.test.js
  src/state/pages/__tests__/reducer.test.js
  src/state/pages/actions.js
  src/state/pages/reducer.js
  src/state/pages/types.js
  src/ui/common/page/PageTreeSelectContainer.js
Labels: approved, do-not-merge/work-in-progress, size/L

#175 ENG-498 Content Type Monolist/Composite Navigation Issue Fix
  src/api/__tests__/contentTemplates.test.js
  src/api/__tests__/pages.test.js
  src/api/contentTemplates.js
  src/state/content-type/__tests__/actions.test.js
  src/state/content-type/__tests__/reducer.test.js
  src/state/content-type/actions.js
  src/state/content-type/reducer.js
  src/state/content-type/selectors.js
  src/state/content-type/types.js
  src/state/users/__tests__/selectors.test.js
  src/ui/common/form/AddContentTypeAttributeForm.js
  src/ui/common/form/ContentTypeMonolistAttributeForm.js
  src/ui/common/form/EditContentTypeAttributeForm.js
  src/ui/content-type/AddContentTypeFormContainer.js
  src/ui/content-type/EditContentTypeFormContainer.js
  src/ui/content-type/__tests__/EditContentTypeFormContainer.test.js
  src/ui/content-type/attributes/AddContentTypeAttributeFormContainer.js
  src/ui/content-type/attributes/EditContentTypeAttributeFormContainer.js
  src/ui/content-type/attributes/monolist/MonolistAttributeFormContainer.js
Labels: approved, size/XL

#176 ENG-582 hide cms menu items if not enough permissions
  package.json
  src/ui/common/LinkMenu.js
Labels: size/L

#178 ENG-466 Enable use-credentials on cropper tool
  src/ui/assets/cropper/AssetPhotoCropper.js
Labels: approved, size/XS
