Repository entando/entando-cms, pull requests merged in 2020-10, with the labels that each got.

#288 ENG-1079 publish content widget
  src/api/contents.js
  src/app-init/routes.js
  src/locales/en.js
  src/locales/it.js
  src/sass/widgets/forms/SingleContentConfigFormBody.scss
  src/testutils/mocks/contents.js
  src/ui/add-content/AddContentFormContainer.js
  src/ui/contents/ContentsTable.js
  src/ui/widget-forms/contents-filter/ContentsFilterBrowser.js
  src/ui/widget-forms/publish-single-content-config/ContentTableRow.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigContainer.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigFormBody.js
Labels: approved, size/L

#289 ENG-1079: adding a missing export
  src/ui/widget-forms/publish-single-content-config/ContentTableRow.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigFormBody.js
Labels: approved, size/XS

#292 ENG-1377 content list card pagination page size
  package-lock.json
  src/ui/contents/list-card/ContentListCard.js
  src/ui/contents/list-card/ContentListCardContainer.js
Labels: approved, size/S

#291 ENG-1270: showing translation warning accordingly to user preferences flag
  src/state/user-preferences/selectors.js
  src/testutils/mocks/editContent.js
  src/ui/add-content/AddContentFormContainer.js
  src/ui/add-content/__tests__/AddContentFormContainer.test.js
  src/ui/common/StickySave.js
  src/ui/edit-content/EditContentFormContainer.js
  src/ui/edit-content/__tests__/EditContentFormContainer.test.js
Labels: approved, size/M

#290 ENG-1253 implement tutorial
  package.json
  src/api/pages.js
  src/locales/en.js
  src/locales/it.js
  src/state/app-tour/__tests__/actions.test.js
  src/state/app-tour/__tests__/reducer.test.js
  src/state/app-tour/__tests__/selectors.test.js
  src/state/app-tour/actions.js
  src/state/app-tour/const.js
  src/state/app-tour/reducer.js
  src/state/app-tour/selectors.js
  src/state/app-tour/types.js
  src/state/pages/__tests__/actions.test.js
  src/state/pages/actions.js
  src/ui/widget-forms/contents-filter/ContentsFilterBrowserContainer.js
  src/ui/widget-forms/contents-filter/ContentsFilterModal.js
  src/ui/widget-forms/contents-filter/ContentsFilterTable.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigContainer.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigFormBody.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigTour.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigTourContainer.js
Labels: approved, size/XL

#293 ENG-1253 fix content widget tutorial back actions
  src/ui/common/modal/GenericModal.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigFormBody.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigTour.js
Labels: approved, size/S

#294 ENG-1270: checking for amendments
  src/state/edit-content/__tests__/actions.test.js
  src/state/edit-content/actions.js
  src/ui/common/StickySave.js
  src/ui/edit-content/EditContentFormContainer.js
Labels: approved, size/S

#295 ENG-1375 implement email attribute for CMS
  src/helpers/__tests__/attrValidation.test.js
  src/helpers/attrValidation.js
  src/state/content-type/const.js
  src/ui/common/contenttype-attributes/AttributeListTableActions.js
  src/ui/common/contenttype-attributes/AttributeRole.js
  src/ui/common/form/RoleSelectRenderer.js
  src/ui/edit-content/content-attributes/AttributeField.js
  src/ui/edit-content/content-attributes/EmailAttributeField.js
Labels: approved, size/L

#296 ENG-1375 follow open/close principle
  src/helpers/__tests__/attrValidation.test.js
  src/helpers/attrValidation.js
  src/ui/edit-content/content-attributes/AttributeField.js
Labels: approved, size/M

#297 ENG-1378 new UX integration on Content Form
  package-lock.json
  src/locales/en.js
  src/locales/it.js
  src/sass/assets/AssetsList.scss
  src/sass/common/CMSShell.scss
  src/sass/common/SectionTitle.scss
  src/sass/common/content/ContentFormFieldCollapse.scss
  src/sass/common/form/RenderListField.scss
  src/sass/edit-content/EditContentForm.scss
  src/sass/index.scss
  src/ui/add-content/AddContentPage.js
  src/ui/assets/AssetsList.js
  src/ui/common/CMSPageTitle.js
  src/ui/common/SectionTitle.js
  src/ui/common/content/ContentFormFieldCollapse.js
  src/ui/common/form/RenderListField.js
  src/ui/common/form/RenderListFieldItem.js
  src/ui/common/rich-text-editor/RichTextEditor.js
  src/ui/edit-content/EditContentForm.js
  src/ui/edit-content/EditContentPage.js
  src/ui/edit-content/__tests__/EditContentForm.test.js
  src/ui/edit-content/content-attributes/AttributeField.js
  src/ui/edit-content/content-attributes/AttributeFields.js
  src/ui/edit-content/content-attributes/CompositeAttributeField.js
  src/ui/edit-content/content-attributes/ContentAttributes.js
  src/ui/edit-content/content-attributes/ImageAttributeField.js
  src/ui/edit-content/content-attributes/LinkAttributeField.js
  src/ui/edit-content/content-attributes/MonolistAttributeField.js
  src/ui/edit-content/content-attributes/__tests__/AttributeField.test.js
Labels: approved, size/XL

#298 ENG-1085 Implement contents table tooltip
  src/sass/contents/Contents.scss
  src/ui/contents/ContentsTable.js
Labels: approved, size/M

#299 ENG-1413: Fix `userPreferences` on standalone CMS app
  src/state/user-preferences/selectors.js
Labels: approved, size/XS
