Repository entando/entando-cms, pull requests merged in 2020-09, with the labels that each got.

#278 ENG-538 re-implement table column localization for attribute name
  src/ui/common/contenttype-attributes/AttributeListTable.js
  src/ui/common/contenttype-attributes/AttributeListTableActions.js
  src/ui/content-type/AddContentTypeForm.js
  src/ui/content-type/AddContentTypeFormContainer.js
  src/ui/content-type/EditContentTypeFormContainer.js
Labels: approved, size/S

#279 ENG-1090: Add alert or warning when creating new content with missing translation
  src/locales/en.js
  src/locales/it.js
  src/state/content-settings/__tests__/actions.test.js
  src/state/edit-content/__tests__/actions.test.js
  src/state/edit-content/__tests__/reducer.test.js
  src/state/edit-content/actions.js
  src/state/edit-content/reducer.js
  src/state/edit-content/selectors.js
  src/state/edit-content/types.js
  src/ui/add-content/AddContentFormContainer.js
  src/ui/common/cancel-modal/ConfirmCancelModal.js
  src/ui/edit-content/EditContentForm.js
  src/ui/edit-content/EditContentFormContainer.js
Labels: approved, size/L

#280 ENG-538 i18n content form attributes
  src/ui/edit-content/content-attributes/AttributeField.js
  src/ui/edit-content/content-attributes/AttributeFields.js
  src/ui/edit-content/content-attributes/ContentAttributes.js
  src/ui/edit-content/content-attributes/ContentAttributesContainer.js
Labels: approved, size/M

#281 ENG-1091 refactoring around content form codebase for better keyboard tabbing experience
  package-lock.json
  package.json
  src/sass/assets/AssetsAdvancedFilter.scss
  src/sass/categories/common/CategoryTreeInput.scss
  src/sass/categories/common/CategoryTreeSelector.scss
  src/sass/categories/filter/CategoryTreeFilter.scss
  src/sass/common/MultiSelectRenderer.scss
  src/sass/common/form/RenderRadioInput.scss
  src/sass/index.scss
  src/state/categories/__tests__/actions.test.js
  src/state/categories/actions.js
  src/ui/assets/AssetsAdvancedSearch.js
  src/ui/categories/common/CategoryTreeSelector.js
  src/ui/categories/common/CategoryTreeSelectorContainer.js
  src/ui/categories/common/CategoryTreeSelectorRow.js
  src/ui/categories/filter/CategoryTreeFilter.js
  src/ui/categories/filter/CategoryTreeFilterItem.js
  src/ui/common/SectionTitle.js
  src/ui/common/accessibility/KeyCodes.js
  src/ui/common/category/CategoryTreeItem.js
  src/ui/common/category/RenderCategoryTreeInput.js
  src/ui/common/form/RenderListField.js
  src/ui/common/form/RenderSelectInput.js
  src/ui/common/form/RenderTextInput.js
  src/ui/common/form/__tests__/RenderTextInput.test.js
  src/ui/edit-content/EditContentForm.js
  src/ui/edit-content/content-attributes/AttributeField.js
  src/ui/edit-content/content-attributes/AttributeFields.js
  src/ui/edit-content/content-attributes/BooleanAttributeField.js
  src/ui/edit-content/content-attributes/CompositeAttributeField.js
  src/ui/edit-content/content-attributes/ContentAttributes.js
  src/ui/edit-content/content-attributes/ThreeStateAttributeField.js
Labels: approved, size/XL

#283 ENG-1091 minor fix on focus style
  src/sass/categories/common/CategoryTreeSelector.scss
  src/ui/categories/common/CategoryTreeSelectorRow.js
Labels: approved, size/XS

#282 ENG-722 Widget config def exports to utilize for widget form
  package.json
  src/babel.js
  src/ui/widget-forms/ContentConfigFormBody.js
  src/ui/widget-forms/ContentsQueryConfig.js
  src/ui/widget-forms/ContentsQueryConfigContainer.js
  src/ui/widget-forms/MultipleContentsConfigContainer.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigContainer.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigFormBody.js
Labels: approved, size/XXL

#284 ENG-1228: change content attribute 'name' to 'names' to be support mult-languages
  src/ui/common/contenttype-attributes/AttributeInfo.js
  src/ui/common/contenttype-attributes/AttributeListTableActions.js
  src/ui/edit-content/content-attributes/AttributeField.js
  src/ui/edit-content/content-attributes/AttributeFields.js
Labels: size/S

#285 ENG-722 singleconfigcontent on page refresh parameters fix
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigFormBody.js
Labels: approved, size/XS

#286 ENG-538 fix attribute localization
  src/ui/edit-content/content-attributes/AttributeField.js
  src/ui/edit-content/content-attributes/AttributeFields.js
Labels: approved, size/XS

#287 ENG-1229 Fill in all language names
  src/locales/en.js
  src/locales/it.js
Labels: approved, size/L
