Repository entando/entando-cms, pull requests merged in 2020-06, with the labels that each got.

#179 ENG-466 asset filename retrieval basis refactored
  src/state/assets/__tests__/selectors.test.js
  src/state/assets/selectors.js
Labels: approved, size/XS

#180 Test jx pr
  src/state/edit-content/actions.js
Labels: size/XS

#181 ENG-586 implement better ux for add content
  src/ui/edit-content/EditContentForm.js
Labels: size/L

#182 ENG-586 add tests for owner group UI
  src/ui/edit-content/EditContentForm.js
  src/ui/edit-content/__tests__/EditContentForm.test.js
Labels: size/L

#183 ENG-584 - permissions on actions on CMS
  package-lock.json
  package.json
  src/__tests__/babel.test.js
  src/api/__tests__/permissions.test.js
  src/api/permissions.js
  src/app-init/ApiManager.js
  src/app-init/routes.js
  src/state/__tests__/rootReducer.test.js
  src/state/permissions/__tests__/actions.test.js
  src/state/permissions/__tests__/reducer.test.js
  src/state/permissions/__tests__/selectors.test.js
  src/state/permissions/actions.js
  src/state/permissions/const.js
  src/state/permissions/reducer.js
  src/state/permissions/selectors.js
  src/state/permissions/types.js
  src/state/rootReducer.js
  src/testutils/mocks/permissions.js
  src/testutils/mocks/users.js
  src/ui/__tests__/App.test.js
  src/ui/common/LinkMenu.js
  src/ui/common/StickySave.js
  src/ui/common/auth/withPermissions.js
  src/ui/contents/Contents.js
  src/ui/contents/ContentsTable.js
Labels: approved, size/XL

#177 ENG-497: rebuild the cms publication widget screen
  package-lock.json
  src/babel.js
  src/locales/en.js
  src/locales/it.js
  src/sass/index.scss
  src/sass/widgets/forms/ContentsFilterModal.scss
  src/sass/widgets/forms/SingleContentConfigFormBody.scss
  src/state/contents/__tests__/actions.test.js
  src/state/contents/__tests__/selectors.test.js
  src/state/contents/actions.js
  src/state/contents/reducer.js
  src/state/contents/selectors.js
  src/state/contents/types.js
  src/state/permissions/__tests__/reducer.test.js
  src/testutils/mocks/users.js
  src/ui/contents/Contents.js
  src/ui/contents/ContentsContainer.js
  src/ui/contents/ContentsFilter.js
  src/ui/widget-forms/ContentTableRenderer.js
  src/ui/widget-forms/MultipleContentsConfigContainer.js
  src/ui/widget-forms/contents-filter/ContentsFilterModal.js
  src/ui/widget-forms/contents-filter/ContentsFilterModalContainer.js
  src/ui/widget-forms/contents-filter/ContentsFilterTable.js
  src/ui/widget-forms/contents-filter/ContentsFilterTabs.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigContainer.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigFormBody.js
Labels: approved, do-not-merge/work-in-progress, size/XXL

#185 ENG-433 amended column ID for content template list
  src/locales/en.js
  src/locales/it.js
  src/ui/content-template/ContentTemplateList.js
  src/ui/content-template/ContentTemplateListItem.js
Labels: approved, size/XS

#184 ENG-648 fix failing babel dependency to support newer node versions
  package.json
Labels: approved, size/S

#186 ENG-542 CMS widget list of contents filter value not showing
  src/ui/common/form/FiltersSelectRenderer.js
  src/ui/widget-forms/ContentsQueryConfig.js
  src/ui/widget-forms/ContentsQueryConfigContainer.js
Labels: approved, size/S

#191 ENG-659 - frontend filter choices for CMS widget
  src/ui/common/form/FiltersSelectRenderer.js
  src/ui/widget-forms/ContentsQueryConfig.js
  src/ui/widget-forms/ContentsQueryConfigContainer.js
Labels: approved, size/M

#188 ENG-634 versioning table
  package.json
  src/api/versioning.js
  src/app-init/routes.js
  src/locales/en.js
  src/locales/it.js
  src/sass/index.scss
  src/sass/versioning/VersioningList.scss
  src/sass/versioning/VersioningSearchForm.scss
  src/state/__tests__/rootReducer.test.js
  src/state/rootReducer.js
  src/state/versioning/__tests__/actions.test.js
  src/state/versioning/__tests__/reducer.test.js
  src/state/versioning/__tests__/selectors.test.js
  src/state/versioning/actions.js
  src/state/versioning/reducer.js
  src/state/versioning/selectors.js
  src/state/versioning/types.js
  src/testutils/mocks/versioning.js
  src/testutils/test-utils.js
  src/ui/App.js
  src/ui/common/LinkMenu.js
  src/ui/versioning/VersioningList.js
  src/ui/versioning/VersioningListContainer.js
  src/ui/versioning/VersioningListItem.js
  src/ui/versioning/VersioningListPage.js
  src/ui/versioning/VersioningSearchForm.js
  src/ui/versioning/VersioningTypes.js
  src/ui/versioning/VersioningTypesContainer.js
  src/ui/versioning/__tests__/VersioningList.test.js
Labels: approved, size/XXL

#194 ENG-636 browse deleted attachements
  package-lock.json
  src/api/__tests__/versioning.test.js
  src/api/versioning.js
  src/locales/en.js
  src/locales/it.js
  src/sass/index.scss
  src/sass/versioning/AttachmentsList.scss
  src/state/versioning/__tests__/actions.test.js
  src/state/versioning/actions.js
  src/testutils/mocks/versioning.js
  src/ui/versioning/VersioningList.js
  src/ui/versioning/VersioningTypes.js
  src/ui/versioning/attachments/AttachmentsList.js
  src/ui/versioning/attachments/AttachmentsListContainer.js
  src/ui/versioning/attachments/AttachmentsListItem.js
  src/ui/versioning/attachments/AttachmentsListItemActions.js
  src/ui/versioning/attachments/__tests__/AttachmentsList.test.js
Labels: approved, size/XL

#195 ENG-636 did mount fix + pagination
  src/ui/versioning/attachments/AttachmentsList.js
Labels: approved, size/M

#196 Test refactor
  README.md
  package-lock.json
  package.json
  src/api/__mocks__/contentTypes.js
  src/api/__mocks__/versioning.js
  src/testutils/helpers.js
  src/testutils/mocks/versioning.js
  src/testutils/testUtils.js
  src/ui/content-settings/__tests__/ContentSettingsCropRatioInput.test.js
  src/ui/content-settings/__tests__/ContentSettingsCropRatios.test.js
  src/ui/edit-content/content-attributes/__tests__/ContentAttributes.test.js
  src/ui/versioning/VersioningList.js
  src/ui/versioning/__tests__/VersioningList.test.js
  src/ui/versioning/__tests__/VersioningListContainer.test.js
  src/ui/versioning/attachments/__tests__/AttachmentsList.test.js
Labels: approved, size/XL

#192 remove deprecated NODE_PATH env var from .env
  .env
Labels: approved, size/XS

#198 ENG-634 connect to real api and implement filtering correctly
  src/api/__tests__/versioning.test.js
  src/api/versioning.js
  src/testutils/mocks/versioning.js
  src/ui/versioning/VersioningListContainer.js
  src/ui/versioning/VersioningListItem.js
  src/ui/versioning/__tests__/VersioningListContainer.test.js
  src/ui/versioning/attachments/AttachmentsListContainer.js
Labels: approved, size/L

#193 ENG-640 edit content history
  src/api/__mocks__/versioning.js
  src/api/__tests__/versioning.test.js
  src/api/versioning.js
  src/locales/en.js
  src/locales/it.js
  src/state/versioning/__tests__/actions.test.js
  src/state/versioning/actions.js
  src/testutils/mocks/versioning.js
  src/ui/edit-content/EditContentForm.js
  src/ui/versioning/SingleContentVersioningHistory.js
  src/ui/versioning/SingleContentVersioningHistoryContainer.js
  src/ui/versioning/SingleContentVersioningHistoryItem.js
  src/ui/versioning/__tests__/SingleContentVersioningHistoryContainer.test.js
Labels: approved, size/L

#200 ENG-678 implement restore content functionality
  src/locales/en.js
  src/locales/it.js
  src/ui/App.js
  src/ui/versioning/RestoreContentVersionModal.js
  src/ui/versioning/RestoreContentVersionModalContainer.js
  src/ui/versioning/SingleContentVersioningDetailsPage.js
  src/ui/versioning/SingleContentVersioningHistory.js
  src/ui/versioning/SingleContentVersioningHistoryContainer.js
  src/ui/versioning/SingleContentVersioningHistoryItem.js
  src/ui/versioning/VersioningListItem.js
Labels: approved, size/L

#201 ENG-659 CMS widget config on user filtering with listed content type attributes
  package.json
  src/locales/en.js
  src/locales/it.js
  src/sass/common/form/FilterValueOptionSelector.scss
  src/sass/common/form/RenderDateFilterInput.scss
  src/sass/index.scss
  src/state/content-type/selectors.js
  src/ui/common/form/FilterValueOptionSelector.js
  src/ui/common/form/FiltersSelectRenderer.js
  src/ui/common/form/RenderDateFilterInput.js
  src/ui/versioning/ContentVersioningDetails.js
  src/ui/widget-forms/ContentsQueryConfig.js
  src/ui/widget-forms/ContentsQueryConfigContainer.js
Labels: approved, size/XXL

#199 ENDOC-34 Update README
  README.md
Labels: approved, size/XS

#202 ENG-635 restore content version
  src/api/__tests__/versioning.test.js
  src/api/versioning.js
  src/state/versioning/__tests__/actions.test.js
  src/state/versioning/actions.js
  src/testutils/helpers.js
  src/testutils/mocks/versioning.js
  src/ui/versioning/RestoreContentVersionModalContainer.js
Labels: approved, size/L

#203 ENG-640 version details
  package.json
  src/api/__mocks__/editContent.js
  src/api/__mocks__/languages.js
  src/api/__mocks__/versioning.js
  src/api/__tests__/versioning.test.js
  src/api/versioning.js
  src/app-init/routes.js
  src/locales/en.js
  src/locales/it.js
  src/sass/variables.scss
  src/sass/versioning/VersioningList.scss
  src/state/assets/selectors.js
  src/state/versioning/__tests__/actions.test.js
  src/state/versioning/__tests__/reducer.test.js
  src/state/versioning/__tests__/selectors.test.js
  src/state/versioning/actions.js
  src/state/versioning/reducer.js
  src/state/versioning/selectors.js
  src/state/versioning/types.js
  src/testutils/mocks/editContent.js
  src/testutils/mocks/versioning.js
  src/ui/App.js
  src/ui/contents/ContentsTable.js
  src/ui/versioning/SingleContentCurrentVersion.js
  src/ui/versioning/SingleContentCurrentVersionContainer.js
  src/ui/versioning/SingleContentVersioningHistory.js
  src/ui/versioning/SingleContentVersioningHistoryContainer.js
  src/ui/versioning/SingleContentVersioningHistoryItem.js
  src/ui/versioning/SingleContentVersioningHistoryPage.js
  src/ui/versioning/VersioningListItem.js
  src/ui/versioning/__tests__/SingleContentCurrentVersionContainer.test.js
  src/ui/versioning/__tests__/SingleContentVersioningHistoryContainer.test.js
  src/ui/versioning/__tests__/VersioningListContainer.test.js
  src/ui/versioning/details/ContentVersionDetails.js
  src/ui/versioning/details/ContentVersionDetailsContainer.js
  src/ui/versioning/details/ContentVersionDetailsPage.js
  src/ui/versioning/details/ContentVersionDetailsValueItem.js
  src/ui/versioning/details/__tests__/ContentVersionDetailsContainer.test.js
  src/ui/widget-forms/contents-filter/ContentsFilterTable.js
Labels: size/XXL

#204 ENG-636 implement browse attachments feature
  src/api/__mocks__/versioning.js
  src/api/__tests__/versioning.test.js
  src/api/versioning.js
  src/locales/en.js
  src/locales/it.js
  src/sass/versioning/AttachmentsList.scss
  src/state/versioning/__tests__/actions.test.js
  src/state/versioning/__tests__/reducer.test.js
  src/state/versioning/__tests__/selectors.test.js
  src/state/versioning/actions.js
  src/state/versioning/reducer.js
  src/state/versioning/selectors.js
  src/state/versioning/types.js
  src/ui/versioning/attachments/AttachmentsList.js
  src/ui/versioning/attachments/AttachmentsListContainer.js
  src/ui/versioning/attachments/AttachmentsListItem.js
  src/ui/versioning/attachments/AttachmentsListItemActions.js
  src/ui/versioning/attachments/__tests__/AttachmentsList.test.js
  src/ui/versioning/common/RemoveResourceModal.js
  src/ui/versioning/common/RemoveResourceModalContainer.js
  src/ui/versioning/images/ImagesListContainer.js
  src/ui/versioning/images/ImagesListItem.js
  src/ui/versioning/images/ImagesListItemActions.js
  src/ui/versioning/images/__tests__/ImagesListContainer.test.js
Labels: size/XL

#207 ENG-652 Versioning Configuration Page
  src/api/versioning.js
  src/locales/en.js
  src/locales/it.js
  src/sass/versioning/VersioningList.scss
  src/state/versioning/__tests__/actions.test.js
  src/state/versioning/__tests__/reducer.test.js
  src/state/versioning/actions.js
  src/state/versioning/reducer.js
  src/state/versioning/types.js
  src/testutils/mocks/versioning.js
  src/ui/versioning/VersioningConfig.js
  src/ui/versioning/VersioningConfigContainer.js
  src/ui/versioning/VersioningTypes.js
Labels: approved, size/L

#208 ENG-638 improve UX
  src/locales/en.js
  src/locales/it.js
  src/state/versioning/__tests__/actions.test.js
  src/state/versioning/actions.js
  src/ui/edit-content/EditContentForm.js
  src/ui/versioning/RestoreContentVersionModalContainer.js
  src/ui/versioning/SingleContentVersioningHistory.js
  src/ui/versioning/images/__tests__/ImagesListContainer.test.js
Labels: size/L

#209 ENG-638 improve UX + action json parsing
  src/state/versioning/actions.js
  src/ui/versioning/SingleContentCurrentVersion.js
  src/ui/versioning/SingleContentCurrentVersionContainer.js
Labels: approved, size/S

#210 ENG-640 implement new logic for status color showing
  src/ui/contents/ContentsTable.js
  src/ui/versioning/SingleContentVersioningHistoryItem.js
  src/ui/versioning/VersioningListItem.js
  src/ui/versioning/__tests__/VersioningListContainer.test.js
Labels: size/S

#211 ENG-640 fix labeling and dates
  package.json
  src/locales/en.js
  src/ui/common/LegacyAdminConsoleMenu.js
  src/ui/versioning/SingleContentVersioningHistory.js
  src/ui/versioning/VersioningList.js
  src/ui/versioning/__tests__/SingleContentVersioningHistoryContainer.test.js
  src/ui/versioning/__tests__/VersioningListContainer.test.js
Labels: approved, size/L

#212 ENG-640 rename labels again
  src/locales/en.js
  src/ui/versioning/SingleContentVersioningHistory.js
  src/ui/versioning/VersioningList.js
  src/ui/versioning/__tests__/SingleContentVersioningHistoryContainer.test.js
  src/ui/versioning/__tests__/VersioningListContainer.test.js
Labels: approved, size/S

#214 ENG-637 ENG-639 - amending recover action buttons
  src/api/__tests__/versioning.test.js
  src/api/versioning.js
  src/locales/en.js
  src/locales/it.js
  src/sass/index.scss
  src/sass/versioning/RecoverResourceModal.scss
  src/state/versioning/__tests__/actions.test.js
  src/state/versioning/actions.js
  src/ui/versioning/attachments/AttachmentsList.js
  src/ui/versioning/attachments/AttachmentsListContainer.js
  src/ui/versioning/attachments/AttachmentsListItemActions.js
  src/ui/versioning/common/RecoverResourceModal.js
  src/ui/versioning/common/RecoverResourceModalContainer.js
  src/ui/versioning/images/ImagesList.js
  src/ui/versioning/images/ImagesListContainer.js
  src/ui/versioning/images/ImagesListItem.js
  src/ui/versioning/images/ImagesListItemActions.js
Labels: approved, size/L

#213 ENG-543 publish contents widget config change on selecting contents
  src/locales/en.js
  src/locales/it.js
  src/sass/common/form/FiltersSelectRenderer.scss
  src/ui/widget-forms/ContentTableRenderer.js
  src/ui/widget-forms/contents-filter/ContentsFilterBrowser.js
  src/ui/widget-forms/contents-filter/ContentsFilterBrowserContainer.js
  src/ui/widget-forms/contents-filter/ContentsFilterModal.js
  src/ui/widget-forms/contents-filter/ContentsFilterModalContainer.js
  src/ui/widget-forms/contents-filter/ContentsFilterTable.js
Labels: approved, size/XL

#215 ENG-716 table columns
  src/babel.js
  src/state/__tests__/rootReducer.test.js
  src/state/contents/__tests__/actions.test.js
  src/state/contents/__tests__/reducer.test.js
  src/state/contents/__tests__/selectors.test.js
  src/state/contents/actions.js
  src/state/contents/reducer.js
  src/state/contents/selectors.js
  src/state/contents/types.js
  src/state/rootReducer.js
  src/state/table-columns/__tests__/actions.test.js
  src/state/table-columns/__tests__/reducer.test.js
  src/state/table-columns/__tests__/selectors.test.js
  src/state/table-columns/actions.js
  src/state/table-columns/reducer.js
  src/state/table-columns/selectors.js
  src/state/table-columns/types.js
  src/ui/common/content/Contents.js
  src/ui/common/content/ContentsContainer.js
  src/ui/contents/Contents.js
  src/ui/contents/ContentsContainer.js
  src/ui/contents/ContentsTabs.js
  src/ui/widget-forms/contents-filter/ContentsFilterBrowserContainer.js
  src/ui/widget-forms/contents-filter/ContentsFilterTabs.js
Labels: approved, size/L

#216 ENG-737 delete content version
  src/api/__tests__/versioning.test.js
  src/api/versioning.js
  src/locales/en.js
  src/locales/it.js
  src/state/versioning/__tests__/actions.test.js
  src/state/versioning/actions.js
  src/testutils/mocks/versioning.js
  src/ui/versioning/DeleteContentVersionModal.js
  src/ui/versioning/DeleteContentVersionModalContainer.js
  src/ui/versioning/RestoreContentVersionModalContainer.js
  src/ui/versioning/SingleContentVersioningHistory.js
  src/ui/versioning/SingleContentVersioningHistoryContainer.js
  src/ui/versioning/SingleContentVersioningHistoryItem.js
Labels: approved, size/L

#217 ENG-717 implement failsafe mechanism if groups is empty array
  src/ui/contents/ContentsTable.js
  src/ui/widget-forms/contents-filter/ContentsFilterTable.js
Labels: approved, size/XS

#218 ENG-543 missed default current column array prop
  src/ui/widget-forms/contents-filter/ContentsFilterBrowser.js
Labels: approved, size/XS

#219 ENG-738 ENG-739 remove resource modal prompt & action
  src/api/__tests__/versioning.test.js
  src/api/versioning.js
  src/locales/en.js
  src/locales/it.js
  src/sass/index.scss
  src/sass/versioning/ResourceModal.scss
  src/state/versioning/__tests__/actions.test.js
  src/state/versioning/actions.js
  src/ui/versioning/attachments/AttachmentsList.js
  src/ui/versioning/attachments/AttachmentsListItemActions.js
  src/ui/versioning/common/RecoverResourceModal.js
  src/ui/versioning/common/RecoverResourceModalContainer.js
  src/ui/versioning/common/RemoveResourceModal.js
  src/ui/versioning/common/RemoveResourceModalContainer.js
  src/ui/versioning/images/ImagesList.js
  src/ui/versioning/images/ImagesListItemActions.js
Labels: approved, size/L
