Repository entando/entando-cms, pull requests merged in 2020-04, with the labels that each got.

#137 ENG-383 implement missing monolist on composite feature
  src/ui/common/form/RenderListField.js
Labels: size/M

#138 ENG-389 change release script
  jenkins-x.yml
Labels: size/XS

#139 ENG-389 change release script
  jenkins-x.yml
Labels: size/S

#141 ENG-200 friendly errors
  package-lock.json
  package.json
Labels: approved, size/S

#142 ENG-397 toolbar fix on multi ckeditor fields
  src/ui/common/form/RenderRichTextEditor.js
  src/ui/common/rich-text-editor/EditorToolbar.js
  src/ui/common/rich-text-editor/RichTextEditor.js
Labels: approved, size/M

#143 ENG-392 link + fullscreen + view source functionality on multiple hypertext editors fix
  src/sass/common/form/RenderRichTextEditor.scss
  src/ui/common/rich-text-editor/RichTextEditor.js
Labels: approved, size/M

#145 ENG-389 cms publish 2
  commands/publish.js
  jenkins-x.yml
Labels: size/S

#146 ENG-389 cms publish 3
  jenkins-x.yml
Labels: size/XS

#147 ENG-389 add master as push and remove logs
  commands/publish.js
  jenkins-x.yml
Labels: size/S

#149 ENG-389 fix version
  .npmrc/..2020_04_30_17_43_58.030537598/npm-auth-token
  .npmrc/..data
  .npmrc/npm-auth-token
  commands/publish.js
  package.json
Labels: size/XS
