Repository entando/entando-cms, pull requests merged in 2020-12, with the labels that each got.

#319 Update @entando/pagetreeselector
  package-lock.json
  package.json
Labels: approved, size/S

#320 ENG-1590 Fix boolean, checkbox, threestate attribute field values
  src/state/edit-content/actions.js
  src/ui/common/StickySave.js
  src/ui/edit-content/content-attributes/AttributeFields.js
  src/ui/edit-content/content-attributes/ThreeStateAttributeField.js
Labels: approved, size/L

#322 ENG-1589 Fix enum attribute settings validation to accept other delim…
  src/ui/common/contenttype-attributes/AttributeEnumSettings.js
Labels: approved, size/XS

#323 ENG-1580 no duplicate for image attribute values
  src/state/edit-content/actions.js
Labels: approved, size/XS

#324 ENG-1585 RTE hypertext attribute resolve on empty values when field is mandatory
  src/helpers/__tests__/attrValidation.test.js
  src/helpers/attrValidation.js
  src/ui/edit-content/content-attributes/AttributeField.js
Labels: approved, size/S

#325 ENG-1591 fix file type filtering
  src/state/assets/actions.js
Labels: approved, size/XS

#326 ENG-1609 fix timestamp causing crash
  src/ui/edit-content/content-attributes/TimestampAttributeField.js
Labels: approved, size/XS

#327 ENG-1563: making templates required on the content type screen
  src/ui/content-type/AddContentTypeForm.js
Labels: approved, size/XS

#328 ENG-1606 Fix link attribute validation
  src/helpers/__tests__/attrValidation.test.js
  src/helpers/attrValidation.js
  src/ui/edit-content/content-attributes/AttributeField.js
  src/ui/edit-content/content-attributes/LinkAttributeField.js
Labels: approved, size/S

#329 ENG-1606 Add additional property check in linkValidate
  src/helpers/attrValidation.js
Labels: approved, size/XS

#335 Revert "ENG-1563: making templates required on the content type screen"
  src/ui/content-type/AddContentTypeForm.js
Labels: approved, size/XS

#339 ENG-1612 fix boolean values being disappeared
  src/state/edit-content/actions.js
Labels: approved, do-not-merge/work-in-progress, size/XS

#338 ENG-1640 fix data lost during content list config refresh
  src/ui/widget-forms/ContentConfigFormBody.js
Labels: approved, do-not-merge/work-in-progress, size/XS

#336 ENG-1611 fix contents pagination problem
  src/ui/contents/status-card/ContentsStatusCardContainer.js
Labels: approved, do-not-merge/work-in-progress, size/XS

#340 ENG-1570 change descriptions to name
  src/locales/en.js
  src/locales/it.js
Labels: approved, size/S

#330 ENG-1598 removing erroneus cosmetic issue on attach attribute labels
  src/ui/edit-content/content-attributes/AttachAttributeField.js
Labels: approved, size/S

#333 ENG-1627 Fix monotext list form validation
  src/ui/common/form/ContentTypeMonolistAttributeForm.js
  src/ui/common/form/RenderListField.js
Labels: approved, do-not-merge/work-in-progress, size/XS

#332 ENG-1603 restricting uploads with group based on content group reference
  src/ui/assets/AssetsUpload.js
  src/ui/assets/modals/upload-assets/UploadAssetModalContainer.js
  src/ui/assets/modals/upload-assets/UploadAssetModalFiles.js
  src/ui/edit-content/content-attributes/AttachAttributeField.js
  src/ui/edit-content/content-attributes/AttributeFields.js
  src/ui/edit-content/content-attributes/ImageAttributeField.js
Labels: approved, size/S

#334 ENG-1631 convert code search to number type
  src/locales/en.js
  src/locales/it.js
  src/ui/common/form/RenderSearchFormInput.js
  src/ui/content-template/ContentTemplateSearchForm.js
Labels: approved, do-not-merge/work-in-progress, size/S

#331 ENG-1602 composite fields are now attached with mainGroup & joinGroups
  src/ui/edit-content/content-attributes/CompositeAttributeField.js
Labels: approved, size/XS

#337 ENG-1613 Fix complex attribute label display when mandatory
  src/helpers/__tests__/attrValidation.test.js
  src/helpers/attrValidation.js
  src/ui/common/form/RenderListField.js
  src/ui/edit-content/content-attributes/AttributeFields.js
  src/ui/edit-content/content-attributes/CompositeAttributeField.js
  src/ui/edit-content/content-attributes/MonolistAttributeField.js
Labels: approved, do-not-merge/work-in-progress, size/M

#341 ENG-1607 amended mandatory validation on composite attributes
  src/helpers/__tests__/attrValidation.test.js
  src/helpers/attrValidation.js
  src/ui/edit-content/content-attributes/AttributeFields.js
  src/ui/edit-content/content-attributes/CompositeAttributeField.js
  src/ui/edit-content/content-attributes/ContentAttributes.js
Labels: approved, size/M

#343 ENG-1599: removing attach attribute value from field results to prompt on providing update translations
  src/state/edit-content/actions.js
  src/ui/edit-content/content-attributes/assets/AssetAttributeFieldInfoContainer.js
Labels: approved, size/S

#342 ENG-1633 Fix timestamp attribute data handling logic if in a complex attribute
  src/ui/edit-content/content-attributes/AttributeFields.js
  src/ui/edit-content/content-attributes/TimestampAttributeField.js
Labels: approved, size/M

#344 ENG-1623 Avoid mutating props in ContentsFilter
  src/ui/contents/ContentsFilter.js
Labels: approved, size/S

#345 ENG-1656 make owner group field required
  src/ui/edit-content/EditContentForm.js
Labels: approved, size/XS

#346 ENG-1607 non-default language fields of a composite attribute should not be mandatory
  src/ui/edit-content/content-attributes/AttributeFields.js
  src/ui/edit-content/content-attributes/CompositeAttributeField.js
Labels: approved, size/S

#347 ENG-1668 Fix composite attribute validation causing app crash
  package-lock.json
  src/helpers/attrValidation.js
Labels: approved, size/XS

#348 ENG-1593 Fix the responsiveness of content list card
  src/sass/contents/ContentListCard.scss
  src/ui/contents/list-card/ContentListCard.js
Labels: approved, size/M

#349 ENG-1647 Remove extractor bean name field from enum attribute settings
  package-lock.json
  src/ui/common/contenttype-attributes/AttributeEnumMapSettings.js
  src/ui/common/contenttype-attributes/AttributeEnumSettings.js
  src/ui/common/contenttype-attributes/__tests__/AttributeEnumMapSettings.test.js
  src/ui/common/contenttype-attributes/__tests__/AttributeEnumSettings.test.js
Labels: approved, size/M

#350 ENG-1608 Fix Date attribute validation
  package-lock.json
  src/helpers/__tests__/attrValidation.test.js
  src/helpers/attrValidation.js
Labels: approved, size/M
