Repository entando/entando-cms, pull requests merged in 2020-08, with the labels that each got.

#257 ENG-971 content workflow
  src/locales/en.js
  src/locales/it.js
  src/sass/common/form/ToggleButtonGroup.scss
  src/sass/index.scss
  src/ui/add-content/AddContentFormContainer.js
  src/ui/common/StickySave.js
  src/ui/common/form/ToggleButtonGroupField.js
  src/ui/contents/ContentsFilter.js
  src/ui/contents/ContentsTabs.js
  src/ui/edit-content/EditContentForm.js
  src/ui/edit-content/EditContentFormContainer.js
  src/ui/widget-forms/contents-filter/ContentsFilterTabs.js
Labels: approved, size/L

#259 ENG-681 owner group filter
  src/api/__tests__/pages.test.js
  src/api/pages.js
  src/state/assets/__tests__/actions.test.js
  src/state/assets/actions.js
  src/state/contents/__tests__/actions.test.js
  src/state/contents/actions.js
  src/state/contents/reducer.js
  src/state/edit-content/__tests__/actions.test.js
  src/state/pages/actions.js
  src/ui/add-content/AddContentFormContainer.js
  src/ui/assets/AssetsAdvancedSearchContainer.js
  src/ui/assets/AssetsListContainer.js
  src/ui/common/content/ContentList.js
  src/ui/common/content/ContentSearch.js
  src/ui/common/content/Contents.js
  src/ui/common/content/ContentsContainer.js
  src/ui/common/form/RenderRichTextEditor.js
  src/ui/common/form/RenderTextInput.js
  src/ui/common/link-config/LinkConfigContentForm.js
  src/ui/common/link-config/LinkConfigPageForm.js
  src/ui/common/link-config/LinkConfigResourceForm.js
  src/ui/common/modal/LinkConfigModal.js
  src/ui/common/page/PageTreeSelectContainer.js
  src/ui/common/rich-text-editor/RichTextEditor.js
  src/ui/contents/ContentsContainer.js
  src/ui/edit-content/EditContentForm.js
  src/ui/edit-content/EditContentFormContainer.js
  src/ui/edit-content/content-attributes/AttachAttributeField.js
  src/ui/edit-content/content-attributes/AttachAttributeFieldContainer.js
  src/ui/edit-content/content-attributes/AttributeField.js
  src/ui/edit-content/content-attributes/AttributeFields.js
  src/ui/edit-content/content-attributes/ContentAttributes.js
  src/ui/edit-content/content-attributes/DateAttributeField.js
  src/ui/edit-content/content-attributes/ImageAttributeField.js
  src/ui/edit-content/content-attributes/ImageAttributeFieldContainer.js
  src/ui/edit-content/content-attributes/LinkAttributeField.js
  src/ui/edit-content/content-attributes/assets/AssetBrowserModal.js
  src/ui/widget-forms/ContentConfigFormBody.js
  src/ui/widget-forms/ContentPickerContainer.js
  src/ui/widget-forms/ContentTableRenderer.js
  src/ui/widget-forms/MultipleContentsConfigContainer.js
  src/ui/widget-forms/contents-filter/ContentsFilterBrowser.js
  src/ui/widget-forms/contents-filter/ContentsFilterBrowserContainer.js
  src/ui/widget-forms/contents-filter/ContentsFilterModal.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigContainer.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigFormBody.js
Labels: approved, size/XL

#260 Eng 976 labels localization formatting
  src/locales/en.js
  src/locales/it.js
  src/ui/assets/AssetsAdvancedSearch.js
  src/ui/versioning/SingleContentVersioningHistoryItem.js
  src/ui/versioning/VersioningListItem.js
  src/ui/versioning/__tests__/SingleContentVersioningHistoryContainer.test.js
Labels: approved, size/M

#262 ENG-971 fixed color for ready unpublished content, restored old conte…
  src/sass/variables.scss
  src/ui/contents/ContentsTable.js
  src/ui/contents/status-card/ContentsStatusCard.js
Labels: approved, size/S

#263 ENG-744 ENG-985 map widget config by action
  src/babel.js
Labels: approved, size/S

#261 fixing selector to create the downloadUrl
  src/state/assets/__tests__/selectors.test.js
  src/state/assets/selectors.js
Labels: approved, size/S

#264 ENG-993 fix occasional blank page when saving a content
  src/ui/edit-content/content-attributes/AttributeFields.js
Labels: approved, size/XS

#265 ENG-991: Page dashboard tiles fixes
  src/state/content-type/actions.js
  src/ui/contents/list-card/ContentListCardContainer.js
Labels: approved, size/XS

#266 ENG-994: Content attributes: no mandatory attributes for not-default languages
  src/ui/edit-content/content-attributes/AttributeFields.js
  src/ui/edit-content/content-attributes/ContentAttributes.js
Labels: size/S

#267 ENG-713 Re-implement content download as xls
  src/ui/contents/ContentsTabs.js
Labels: approved, size/S

#268 ENG-996 fix content list widget settings
  src/helpers/__tests__/joinGroups.test.js
  src/helpers/joinGroups.js
  src/state/assets/actions.js
  src/ui/widget-forms/ContentPickerContainer.js
Labels: approved, size/M

#269 ENG-996 fix content list widget settings
  src/state/contents/actions.js
Labels: approved, size/XS

#270 ENG-798 Autocomplete items issue fix
  src/state/content-template/__tests__/selectors.test.js
  src/state/content-template/selectors.js
  src/state/content-type/__tests__/actions.test.js
  src/state/content-type/__tests__/selectors.test.js
  src/state/content-type/actions.js
  src/state/content-type/const.js
  src/state/content-type/selectors.js
  src/ui/common/form/RenderContentTemplateInput.js
  src/ui/common/form/RenderDropdownTypeaheadInput.js
  src/ui/content-template/AddContentTemplateForm.js
  src/ui/content-template/AddContentTemplateFormContainer.js
  src/ui/content-template/EditContentTemplateFormContainer.js
Labels: approved, size/XL

#271 trigger JX for CMS autocomplete update
  src/state/content-type/const.js
Labels: approved, size/XS

#272 ENG-1044 autocomplete issue fix on suggestion redundancy
  src/ui/common/form/RenderContentTemplateInput.js
Labels: approved, size/XS

#273 ENG-1095 implement collapsable sections for ease of use
  src/ui/add-content/AddContentFormContainer.js
  src/ui/common/SectionTitle.js
  src/ui/edit-content/EditContentForm.js
  src/ui/edit-content/EditContentFormContainer.js
Labels: approved, size/L

#275 ENG-1095 fix overlapping bottom bar
  src/sass/edit-content/EditContentForm.scss
Labels: approved, size/S

#274 making ownerGroup enabled when adding a new content
  src/ui/edit-content/EditContentForm.js
Labels: approved, size/S

#276 fixing add content screen
  src/ui/edit-content/EditContentForm.js
Labels: approved, size/XS
