Repository entando/entando-cms, pull requests merged in 2020-07, with the labels that each got.

#221 ENG-729 attributes list options for attribute type list fix
  src/state/content-type/selectors.js
Labels: approved, size/S

#220 ENG-791 ENG-792 resource on versioning permissions fix
  src/locales/en.js
  src/locales/it.js
  src/ui/assets/DeleteAssetModalContainer.js
  src/ui/common/LinkMenu.js
  src/ui/versioning/VersioningTypes.js
  src/ui/versioning/VersioningTypesContainer.js
Labels: approved, size/L

#222 ENG-638 deleted images browsing
  src/sass/assets/AssetsList.scss
  src/testutils/mocks/versioning.js
  src/ui/versioning/VersioningListItem.js
  src/ui/versioning/attachments/AttachmentsListItem.js
  src/ui/versioning/attachments/__tests__/AttachmentsList.test.js
  src/ui/versioning/common/RecoverResourceModal.js
  src/ui/versioning/images/ImagesList.js
  src/ui/versioning/images/ImagesListItem.js
Labels: size/M

#223 ENG-737 remove error toast...
  src/state/versioning/actions.js
Labels: approved, size/XS

#224 ENG-640 dependencies updated - primarily for new formatDate util helper
  package-lock.json
  package.json
  src/testutils/mocks/editContent.js
  src/testutils/mocks/versioning.js
  src/ui/versioning/__tests__/SingleContentCurrentVersionContainer.test.js
Labels: approved, size/M

#225 ENG-686 implement contents status card
  src/babel.js
  src/locales/en.js
  src/locales/it.js
  src/ui/contents/status-card/ContentsStatusCard.js
  src/ui/contents/status-card/ContentsStatusCardContainer.js
Labels: size/M

#226 ENG-686 change babel export properties
  src/babel.js
Labels: approved, size/XS

#227 ENG-686 apply new changes
  src/sass/contents/ContentsStatusCard.scss
  src/sass/index.scss
  src/ui/common/content/Contents.js
  src/ui/common/content/ContentsContainer.js
  src/ui/contents/status-card/ContentsStatusCard.js
  src/ui/contents/status-card/ContentsStatusCardContainer.js
Labels: approved, size/M

#228 ENG-759 composite attribute content form fix
  src/ui/edit-content/content-attributes/AttributeFields.js
  src/ui/edit-content/content-attributes/CompositeAttributeField.js
  src/ui/edit-content/content-attributes/ImageAttributeFieldContainer.js
Labels: approved, size/M

#229 ENG-759 composite saving fix on link & date
  src/state/edit-content/actions.js
  src/ui/edit-content/content-attributes/LinkAttributeField.js
Labels: approved, size/M

#230 ENG-874 fix content status styling
  src/locales/en.js
  src/locales/it.js
  src/sass/contents/ContentsStatusCard.scss
  src/ui/contents/status-card/ContentsStatusCard.js
Labels: size/M

#231 ENG-772: Fix nomenclature according to new glossary
  src/locales/en.js
  src/locales/it.js
Labels: approved, size/XS

#232 ENG-857 UX Quick Wins: Modify appearance and positioning of buttons
  src/sass/patternfly.scss
  src/ui/content-template/ContentTemplateListPage.js
  src/ui/content-type/ContentTypeListPage.js
Labels: approved, size/M

#233 ENG-887 apply cms responsiveness css fixes
  src/ui/add-content/AddContentPage.js
  src/ui/common/StickySave.js
  src/ui/edit-content/EditContentForm.js
  src/ui/edit-content/EditContentPage.js
Labels: approved, size/S

#234 ENG-891 fix labels
  src/locales/en.js
  src/locales/it.js
  src/ui/contents/ContentsFilter.js
  src/ui/widget-forms/ContentConfigFormBody.js
  src/ui/widget-forms/ContentsQueryConfig.js
Labels: approved, size/M

#235 ENG-714 toast message shown when crop value is invalid
  src/locales/en.js
  src/locales/it.js
  src/ui/content-settings/ContentSettingsCropRatioInput.js
  src/ui/content-settings/ContentSettingsCropRatios.js
  src/ui/content-settings/ContentSettingsCropRatiosContainer.js
Labels: approved, size/M

#236 ENG-892 hide content xls download
  src/ui/contents/ContentsTabs.js
Labels: approved, size/S

#237 amend OWNERS and OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
Labels: approved, size/M

#238 ENG-714 fix labels
  src/locales/it.js
Labels: size/XS

#239 ENG-797: CMS/Digital Assets: "Documents" tab shows nothing after long running spinner
  src/locales/en.js
  src/ui/assets/AssetsList.js
Labels: size/XS

#240 ENG-891 i18n fixes
  OWNERS
  OWNERS_ALIASES
  src/locales/en.js
  src/locales/it.js
  src/testutils/helpers.js
  src/ui/common/paginatorMessages.js
  src/ui/content-template/ContentTemplateList.js
  src/ui/content-template/__tests__/ContentTemplateList.test.js
  src/ui/content-type/ContentTypeList.js
  src/ui/content-type/__tests__/ContentTypeList.test.js
  src/ui/contents/status-card/ContentsStatusCard.js
  src/ui/contents/status-card/ContentsStatusCardContainer.js
  src/ui/versioning/VersioningList.js
  src/ui/versioning/attachments/AttachmentsList.js
  src/ui/versioning/images/ImagesList.js
Labels: size/XL

#241 Eng 891 further label fixes
  src/locales/en.js
  src/locales/it.js
Labels: size/XS

#242 Eng 891 further label fixes
  src/ui/contents/status-card/ContentsStatusCard.js
Labels: approved, size/XS

#243 ENG-909 fix publishing colors
  src/sass/variables.scss
Labels: approved, size/XS

#244 Eng 891 further label fixes
  src/locales/it.js
  src/ui/versioning/SingleContentVersioningHistory.js
Labels: approved, size/S

#245 ENG-908 fix button background contrast
  src/sass/assets/AssetsAdvancedFilter.scss
  src/sass/contents/ContentsFilter.scss
  src/ui/assets/AssetsAdvancedSearch.js
  src/ui/common/StickySave.js
  src/ui/common/content/ContentSearch.js
  src/ui/contents/ContentsFilter.js
Labels: approved, size/S

#247 ENG-860 Asset (image/attach) content must have same source regardless of language
  src/ui/edit-content/content-attributes/AttachAttributeField.js
  src/ui/edit-content/content-attributes/AttachAttributeFieldContainer.js
  src/ui/edit-content/content-attributes/AttributeField.js
  src/ui/edit-content/content-attributes/ImageAttributeField.js
  src/ui/edit-content/content-attributes/ImageAttributeFieldContainer.js
  src/ui/edit-content/content-attributes/assets/AssetAttributeFieldInfoContainer.js
Labels: approved, size/L

#248 ENG-924 implement content list card for app builder dashboard
  src/babel.js
  src/sass/assets/AssetsList.scss
  src/sass/contents/ContentListCard.scss
  src/sass/contents/ContentsStatusCard.scss
  src/sass/index.scss
  src/state/contents/actions.js
  src/state/contents/reducer.js
  src/state/contents/selectors.js
  src/ui/common/LinkMenu.js
  src/ui/contents/list-card/ContentListCard.js
  src/ui/contents/list-card/ContentListCardContainer.js
  src/ui/contents/status-card/ContentsStatusCard.js
Labels: approved, size/L

#246 Update en.js
  src/locales/en.js
  src/locales/it.js
Labels: approved, size/L

#249 ENG-891 amend it labels, add missing translations
  src/locales/en.js
  src/locales/it.js
  src/ui/versioning/SingleContentVersioningHistoryItem.js
  src/ui/versioning/__tests__/SingleContentVersioningHistoryContainer.test.js
Labels: approved, size/M

#250 ENG-935 CMS menu reorganization
  src/app-init/routes.js
  src/helpers/urlUtils.js
  src/locales/en.js
  src/locales/it.js
  src/ui/add-content/AddContentPage.js
  src/ui/common/LinkMenu.js
  src/ui/content-settings/ContentSettingsPage.js
  src/ui/content-template/AddContentTemplatePage.js
  src/ui/content-template/ContentTemplateListPage.js
  src/ui/content-template/EditContentTemplatePage.js
  src/ui/content-type/AddContentTypePage.js
  src/ui/content-type/ContentTypeListPage.js
  src/ui/content-type/EditContentTypePage.js
  src/ui/content-type/attributes/AddContentTypeAttributePage.js
  src/ui/content-type/attributes/EditContentTypeAttributePage.js
  src/ui/content-type/attributes/monolist/MonolistPage.js
  src/ui/contents/ContentsPage.js
  src/ui/edit-content/EditContentPage.js
Labels: approved, size/L

#251 ENG-935 fix labels
  src/locales/en.js
  src/locales/it.js
Labels: approved, size/S

#252 ENG-906 fix contentlist tile issues
  src/locales/en.js
  src/locales/it.js
  src/ui/contents/list-card/ContentListCard.js
  src/ui/contents/status-card/ContentsStatusCard.js
Labels: approved, size/S

#253 ENG-891 amend labels, added i18n for missing parts of the CMS
  src/locales/en.js
  src/locales/it.js
  src/state/contents/reducer.js
  src/ui/assets/AssetsList.js
  src/ui/common/StickySave.js
  src/ui/common/content/ContentList.js
  src/ui/common/content/ContentSearch.js
  src/ui/common/form/RenderVersionText.js
  src/ui/contents/ContentsFilter.js
  src/ui/contents/ContentsTable.js
  src/ui/edit-content/EditContentForm.js
  src/ui/edit-content/content-attributes/ContentAttributes.js
  src/ui/versioning/DeleteContentVersionModal.js
  src/ui/widget-forms/contents-filter/ContentsFilterTable.js
Labels: approved, size/L

#256 ENG-906 amend content dashboard tiles
  src/locales/en.js
  src/locales/it.js
  src/ui/contents/ContentsTable.js
  src/ui/contents/list-card/ContentListCard.js
  src/ui/contents/status-card/ContentsStatusCard.js
  src/ui/versioning/SingleContentCurrentVersion.js
  src/ui/widget-forms/contents-filter/ContentsFilterTable.js
Labels: approved, size/M

#255 ENG-962: AppBuilder: In Assets subsection. if the document name is too long, text formatting problem
  src/sass/assets/DeleteContentModal.scss
  src/sass/index.scss
  src/ui/assets/DeleteAssetModal.js
Labels: approved, size/XS

#258 ENG-969 Localize table columns
  src/ui/common/content/Contents.js
  src/ui/contents/Contents.js
  src/ui/widget-forms/contents-filter/ContentsFilterBrowser.js
Labels: approved, size/L
