Repository entando/entando-cms, pull requests merged in 2020-11, with the labels that each got.

#301 ENG-1108 copy contents to other languages, translation notif improvement, copy text on (hyper)text fields
  package-lock.json
  package.json
  src/locales/en.js
  src/locales/it.js
  src/sass/common/CMSShell.scss
  src/sass/common/StickySave.scss
  src/sass/common/form/RenderTextAreaInput.scss
  src/sass/common/form/RenderTextInput.scss
  src/sass/edit-content/EditContentForm.scss
  src/sass/index.scss
  src/sass/variables.scss
  src/state/edit-content/__tests__/actions.test.js
  src/state/edit-content/actions.js
  src/testutils/mocks/contentType.js
  src/testutils/mocks/editContent.js
  src/ui/add-content/AddContentPage.js
  src/ui/common/StickySave.js
  src/ui/common/button/CopyTextButton.js
  src/ui/common/content/ContentFormFieldCollapse.js
  src/ui/common/form/RenderRichTextEditor.js
  src/ui/common/form/RenderTextAreaInput.js
  src/ui/common/form/RenderTextInput.js
  src/ui/common/rich-text-editor/EditorToolbar.js
  src/ui/common/rich-text-editor/RichTextEditor.js
  src/ui/edit-content/EditContentForm.js
  src/ui/edit-content/EditContentPage.js
  src/ui/edit-content/content-attributes/AttributeField.js
  src/ui/edit-content/content-attributes/ContentAttributes.js
  src/ui/edit-content/content-attributes/ContentAttributesContainer.js
  src/ui/edit-content/content-attributes/HypertextAttributeField.js
  src/ui/edit-content/content-attributes/TextAttributeField.js
  src/ui/edit-content/content-attributes/__tests__/ContentAttributes.test.js
  src/ui/edit-content/content-attributes/__tests__/ContentAttributesContainer.test.js
Labels: approved, size/XXL

#302 ENG-1429: Asset created by an admin doesn't update automatically after editing it
  src/ui/assets/AssetsListItem.js
Labels: approved, size/XS

#303 ENG-1434 Fix issues for content with a very long description
  package-lock.json
  src/sass/assets/DeleteContentModal.scss
  src/sass/index.scss
  src/sass/patternfly.scss
  src/ui/contents/DeleteContentModal.js
  src/ui/contents/PublishContentModal.js
  src/ui/edit-content/EditContentForm.js
Labels: approved, size/S

#304 ENG-1483 Fix incorrect content id reference in EditContentFormContainer
  src/ui/edit-content/EditContentFormContainer.js
Labels: approved, size/XS

#305 ENG-1402 remove tutorial steps from cms
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigFormBody.js
Labels: approved, size/XS

#306 ENG-1430 Fix svg asset issues
  package-lock.json
  package.json
  src/helpers/__tests__/imageUtils.test.js
  src/helpers/imageUtils.js
  src/state/assets/__tests__/actions.test.js
  src/state/assets/actions.js
Labels: approved, size/L

#307 ENG-1402 remove unused texts
  src/locales/en.js
  src/locales/it.js
Labels: approved, size/S

#309 ENG-1495 content type attribute roles on assuring a role only to a single attribute
  src/api/__tests__/contentTypes.test.js
  src/api/contentTypes.js
  src/state/content-type/__tests__/actions.test.js
  src/state/content-type/__tests__/selectors.test.js
  src/state/content-type/actions.js
  src/state/content-type/selectors.js
  src/ui/common/contenttype-attributes/AttributeRole.js
  src/ui/common/form/RoleSelectRenderer.js
  src/ui/content-type/EditContentTypeFormContainer.js
  src/ui/content-type/attributes/AddContentTypeAttributeFormContainer.js
  src/ui/content-type/attributes/EditContentTypeAttributeFormContainer.js
  src/ui/content-type/attributes/monolist/MonolistAttributeFormContainer.js
Labels: approved, size/L

#310 ENG-1528 amend add/edit content CTA to make it blue (it's the primary…
  src/ui/common/StickySave.js
Labels: approved, size/XS

#311 ENG-1527 fix link text resetting
  src/ui/contents/ContentsTable.js
  src/ui/edit-content/content-attributes/LinkAttributeField.js
Labels: approved, size/M

#312 ENG-1529: content management greyed out kebab function are usable even if they should not
  src/sass/contents/Contents.scss
Labels: approved, size/XS

#313 ENG-1530 Optimize content edit form
  src/state/user-preferences/selectors.js
  src/ui/common/form/DebouncedInput.js
  src/ui/edit-content/EditContentForm.js
  src/ui/edit-content/content-attributes/ContentAttributes.js
  src/ui/edit-content/content-attributes/EmailAttributeField.js
  src/ui/edit-content/content-attributes/HypertextAttributeField.js
  src/ui/edit-content/content-attributes/LongtextAttributeField.js
  src/ui/edit-content/content-attributes/MonotextAttributeField.js
  src/ui/edit-content/content-attributes/NumberAttributeField.js
  src/ui/edit-content/content-attributes/TextAttributeField.js
  src/ui/edit-content/content-attributes/__tests__/ContentAttributes.test.js
  src/ui/versioning/SingleContentVersioningHistoryItem.js
Labels: approved, size/L

#314 ENG-1531 cosmetic issues addressed points 3 & 8
  package-lock.json
  src/locales/en.js
  src/locales/it.js
  src/sass/content-template/ContentTemplateList.scss
  src/sass/contents/ContentsFilter.scss
  src/state/content-settings/const.js
  src/ui/assets/AssetsAdvancedSearch.js
  src/ui/content-settings/ContentSettingsGeneral.js
  src/ui/content-template/ContentTemplateListPage.js
  src/ui/content-template/ContentTemplateSearchForm.js
  src/ui/content-template/__tests__/ContentTemplateSearchForm.test.js
  src/ui/contents/ContentsFilter.js
Labels: approved, size/M

#315 ENG-1480 fixes about search assets by date range and validations added
  src/locales/en.js
  src/locales/it.js
  src/state/assets/actions.js
  src/ui/assets/AssetsAdvancedSearch.js
  src/ui/common/form/RenderDatePickerInput.js
Labels: approved, size/M

#317 ENG-1530 Cancel timeout on unmount in RichTextEditor to avoid memory …
  src/ui/common/rich-text-editor/RichTextEditor.js
Labels: approved, size/XS

#318 ENG-1544 unexpected item counts in assets + included other entities to avoid conflict of pagination data
  package-lock.json
  src/state/assets/actions.js
  src/state/content-template/actions.js
  src/state/content-type/actions.js
  src/state/contents/actions.js
  src/state/groups/actions.js
  src/state/pagination/actions.js
  src/state/pagination/const.js
  src/state/pagination/selectors.js
  src/state/permissions/actions.js
  src/state/users/actions.js
  src/state/versioning/actions.js
  src/ui/assets/AssetsListContainer.js
  src/ui/common/content/ContentsContainer.js
  src/ui/content-template/ContentTemplateListContainer.js
  src/ui/content-type/ContentTypeListContainer.js
  src/ui/contents/ContentsContainer.js
  src/ui/versioning/SingleContentVersioningHistoryContainer.js
  src/ui/versioning/VersioningListContainer.js
  src/ui/versioning/attachments/AttachmentsListContainer.js
  src/ui/versioning/images/ImagesListContainer.js
  src/ui/widget-forms/contents-filter/ContentsFilterBrowserContainer.js
Labels: approved, size/L
