Repository entando/entando-cms, pull requests merged in 2021-05, with the labels that each got.

#384 ENG-2377 fix content template deletion
  src/ui/content-template/ContentTemplateList.js
Labels: approved, size/S

#385 Update README.md
  README.md
Labels: approved, size/XS

#387 ENG-2240 use new api for content status card
  src/api/__tests__/contents.test.js
  src/api/contents.js
  src/state/contents/actions.js
  src/ui/contents/status-card/ContentsStatusCardContainer.js
Labels: approved, size/S

#388 ENG-2370 link config resolve for select content / assets
  src/ui/assets/AssetsList.js
  src/ui/assets/AssetsListContainer.js
  src/ui/common/content/ContentList.js
  src/ui/common/link-config/LinkConfigResourceForm.js
Labels: approved, size/M

#389 ENG-2370 select content list for link config - hard-selecting last checked radio button to avoid reset
  src/ui/common/content/ContentList.js
  src/ui/common/content/Contents.js
  src/ui/common/link-config/LinkConfigContentForm.js
Labels: approved, size/S

#383 ENG-2308 resolve issue on CMS category tree checkboxes that won't show subcategories
  src/state/categories/__tests__/selectors.test.js
  src/state/categories/selectors.js
Labels: approved, size/M

#380 ENG-2198: preventing unnecessary component rerender
  src/ui/assets/AssetsList.js
Labels: approved, size/S

#391 ENG-2308 showstopper resolve on displaying content list and assets list
  src/state/categories/selectors.js
  src/ui/categories/filter/CategoryTypeaheadFilter.js
Labels: approved, size/S

#393 ENG-2310 implement clear quick search functionality
  src/ui/contents/ContentsFilter.js
Labels: approved, size/S

#392 ENG-2379 and ENG-2375 Prevent ContentType form initialization when fetching conten…
  package-lock.json
  src/ui/content-template/AddContentTemplateFormContainer.js
  src/ui/content-template/EditContentTemplateFormContainer.js
  src/ui/widget-forms/ContentsQueryConfigContainer.js
Labels: approved, size/XS

#397 ENG-2265 make page field required
  src/ui/widget-forms/ContentConfigFormBody.js
  src/ui/widget-forms/ContentsQueryConfig.js
  src/ui/widget-forms/MultipleContentsConfigContainer.js
Labels: approved, size/S

#399 ENG-2238 amend payloads and show additional attributes
  src/ui/common/link-config/LinkConfigContentForm.js
  src/ui/common/link-config/LinkConfigContentFormContainer.js
  src/ui/common/link-config/LinkConfigPageForm.js
  src/ui/common/link-config/LinkConfigPageFormContainer.js
  src/ui/common/link-config/LinkConfigResourceForm.js
  src/ui/common/link-config/LinkConfigResourceFormContainer.js
  src/ui/common/link-config/LinkConfigUrlForm.js
  src/ui/common/link-config/LinkConfigUrlFormContainer.js
  src/ui/common/modal/LinkConfigModal.js
  src/ui/common/page/PageTreeSelectContainer.js
  src/ui/edit-content/content-attributes/AttributeFields.js
  src/ui/edit-content/content-attributes/LinkAttributeField.js
Labels: approved, size/L

#395 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, size/XS

#400 Merge ENG-2238 changes into ENG-2287
  src/ui/edit-content/content-attributes/AttributeFields.js
Labels: approved, size/XS

#401 ENG-2412 make link text require if page selected
  src/ui/widget-forms/ContentConfigFormBody.js
  src/ui/widget-forms/ContentsQueryConfig.js
  src/ui/widget-forms/ContentsQueryConfigContainer.js
  src/ui/widget-forms/MultipleContentsConfigContainer.js
Labels: approved, size/M

#403 ENG-2424 moved button near filter list
  src/sass/widgets/forms/ContentsQueryForm.scss
  src/ui/widget-forms/ContentsQueryConfig.js
Labels: approved, size/S

#407 ENG-2161 Fix dashboard contents status counts discrepancy
  package-lock.json
  src/api/__tests__/contents.test.js
  src/api/contents.js
  src/state/contents/__tests__/actions.test.js
  src/state/contents/__tests__/reducer.test.js
  src/state/contents/__tests__/selectors.test.js
  src/state/contents/actions.js
  src/state/contents/reducer.js
  src/state/contents/selectors.js
  src/state/contents/types.js
  src/testutils/mocks/contents.js
  src/ui/contents/status-card/ContentsStatusCard.js
  src/ui/contents/status-card/ContentsStatusCardContainer.js
Labels: approved, size/L

#404 ENG-2291 Amend content group pre-selection logic
  src/api/__tests__/permissions.test.js
  src/api/permissions.js
  src/state/permissions/__tests__/actions.test.js
  src/state/permissions/__tests__/reducer.test.js
  src/state/permissions/__tests__/selectors.test.js
  src/state/permissions/actions.js
  src/state/permissions/reducer.js
  src/state/permissions/selectors.js
  src/state/permissions/types.js
  src/testutils/mocks/permissions.js
  src/ui/add-content/AddContentFormContainer.js
  src/ui/add-content/__tests__/AddContentFormContainer.test.js
Labels: approved, size/L
