Repository entando/entando-cms, pull requests merged in 2021-01, with the labels that each got.

#351 ENG-1681 rich text editor maximize / minimize fix
  src/sass/common/form/RenderRichTextEditor.scss
Labels: approved, size/XS

#353 ENG-1563 avoiding contents with its content types that has no default content template on CMS widget configs
  package-lock.json
  src/locales/en.js
  src/locales/it.js
  src/state/content-type/actions.js
  src/ui/common/modal/GenericModal.js
  src/ui/widget-forms/ContentConfigFormBody.js
  src/ui/widget-forms/ContentsQueryConfig.js
  src/ui/widget-forms/ContentsQueryConfigContainer.js
  src/ui/widget-forms/MultipleContentsConfigContainer.js
  src/ui/widget-forms/publish-single-content-config/NoDefaultWarningModal.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigContainer.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigFormBody.js
Labels: approved, size/L

#354 ENG-1563 content query widget config condition trapping on save
  src/ui/widget-forms/ContentsQueryConfigContainer.js
Labels: approved, size/S

#355 ENG-1696 Fix handling of date list validation rules
  src/state/content-type/actions.js
Labels: approved, size/M

#356 React router update
  package-lock.json
  package.json
Labels: approved, size/L
