Repository entando/entando-cms, pull requests merged in 2021-02, with the labels that each got.

#357 Update README.md
  README.md
Labels: approved, size/XS

#358 ENG-1770 dropdown typeahead component update + implementation
  package-lock.json
  package.json
  src/locales/en.js
  src/locales/it.js
  src/sass/common/form/DropdownTypeahead.scss
  src/ui/common/form/RenderDropdownTypeaheadInput.js
  src/ui/common/form/__tests__/RenderDropdownTypeaheadInput.test.js
  src/ui/content-template/AddContentTemplateForm.js
  src/ui/content-template/AddContentTemplateFormContainer.js
  src/ui/content-template/EditContentTemplateFormContainer.js
  src/ui/contents/Contents.js
  src/ui/contents/ContentsContainer.js
  src/ui/contents/ContentsFilter.js
  src/ui/edit-content/EditContentForm.js
  src/ui/widget-forms/contents-filter/ContentsFilterBrowser.js
  src/ui/widget-forms/contents-filter/ContentsFilterBrowserContainer.js
Labels: approved, size/XL

#361 ENG-1882 implement typehead search for group advanced search
  src/ui/assets/AssetsAdvancedSearch.js
  src/ui/assets/AssetsAdvancedSearchContainer.js
Labels: size/M

#360 ENG-1828 localize cms RTE texts
  src/locales/en.js
  src/locales/it.js
  src/ui/common/rich-text-editor/EditorToolbar.js
Labels: approved, size/M
