Repository entando/entando-cms, pull requests merged in 2021-06, with the labels that each got.

#408 ENG-2311 revert category tree filtering exclusively for category tree selector components
  src/state/categories/selectors.js
  src/state/contents/reducer.js
  src/ui/categories/common/CategoryTreeSelectorContainer.js
Labels: approved, size/M

#409 ENG-2414 adding icon state for expand/collapse in sections of CMS widget options
  src/sass/common/SectionTitle.scss
  src/sass/common/form/FormSectionTitle.scss
  src/sass/index.scss
  src/ui/common/SectionTitle.js
  src/ui/common/form/FormSectionTitle.js
  src/ui/widget-forms/ContentConfigFormBody.js
  src/ui/widget-forms/ContentsQueryConfig.js
  src/ui/widget-forms/publish-single-content-config/SingleContentConfigFormBody.js
Labels: approved, size/L

#410 ENG-2311 expand/collapse all buttons amended in category tree selector field component
  src/sass/categories/list/CategoryTree.scss
  src/state/categories/actions.js
  src/state/categories/selectors.js
  src/ui/categories/common/CategoryTreeSelector.js
  src/ui/categories/common/CategoryTreeSelectorContainer.js
Labels: approved, size/M

#411 ENG-2293: adding feedback when copy button is clicked
  src/locales/en.js
  src/locales/it.js
  src/ui/edit-content/content-attributes/ContentAttributesContainer.js
Labels: approved, size/S

#413 ENG-2381: integrating new clone API, changing default mode to list
  src/api/__tests__/contents.test.js
  src/api/contents.js
  src/state/contents/__tests__/actions.test.js
  src/state/contents/actions.js
  src/ui/contents/ContentsContainer.js
Labels: approved, size/M

#414 ENG-2288 Make group permissions alphabetically sorted in add content …
  package-lock.json
  src/state/permissions/actions.js
  src/ui/add-content/AddContentFormContainer.js
Labels: approved, size/S

#415 ENG-2457 Remove unused and obsolete dockerfile
  Dockerfile
Labels: approved, size/XS

#416 ENG-2301 Change attribute enum and enum map settings validation to al…
  package-lock.json
  src/ui/common/contenttype-attributes/AttributeEnumMapSettings.js
  src/ui/common/contenttype-attributes/AttributeEnumSettings.js
Labels: approved, size/XS

#417 ENG-2367 implement date validations
  src/ui/common/contenttype-attributes/AttributesDateSettings.js
  src/ui/common/form/RenderDatePickerInput.js
Labels: approved, size/L
