Repository entando/entando-cms, pull requests merged in 2021-03, with the labels that each got.

#363 ENG-1915 enable content validator crud content and access versioning
  src/ui/contents/list-card/ContentListCard.js
  src/ui/contents/status-card/ContentsStatusCard.js
  src/ui/versioning/VersioningConfigContainer.js
  src/ui/versioning/VersioningTypesContainer.js
Labels: approved, size/S

#364 ENG-1796 implement DataTable component on Versioning List
  package-lock.json
  src/ui/versioning/VersioningList.js
  src/ui/versioning/VersioningListContainer.js
  src/ui/versioning/VersioningListItem.js
Labels: approved, size/L

#365 ENG-1923 amended category typeahead field component for advanced search utility
  package-lock.json
  src/locales/en.js
  src/locales/it.js
  src/sass/contents/ContentsFilter.scss
  src/state/assets/__tests__/actions.test.js
  src/state/assets/__tests__/reducer.test.js
  src/state/assets/actions.js
  src/state/assets/reducer.js
  src/state/contents/__tests__/actions.test.js
  src/state/contents/__tests__/reducer.test.js
  src/state/contents/actions.js
  src/state/contents/reducer.js
  src/ui/assets/AssetsList.js
  src/ui/categories/filter/CategoryTreeFilterContainer.js
  src/ui/categories/filter/CategoryTypeaheadFilter.js
  src/ui/categories/filter/CategoryTypeaheadFilterContainer.js
  src/ui/contents/ContentsFilter.js
  src/ui/contents/JoinCategoriesModal.js
Labels: approved, size/L

#366 ENG-2024 Content list tables implemented with DataTable
  package-lock.json
  package.json
  src/babel.js
  src/sass/contents/Contents.scss
  src/state/assets/__tests__/actions.test.js
  src/state/assets/actions.js
  src/state/assets/const.js
  src/state/contents/__tests__/actions.test.js
  src/state/contents/actions.js
  src/state/contents/const.js
  src/state/contents/reducer.js
  src/state/contents/types.js
  src/ui/assets/AssetsList.js
  src/ui/assets/AssetsListContainer.js
  src/ui/common/content/ContentList.js
  src/ui/common/content/Contents.js
  src/ui/common/content/ContentsContainer.js
  src/ui/contents/Contents.js
  src/ui/contents/ContentsContainer.js
  src/ui/contents/ContentsTable.js
  src/ui/contents/ContentsTabs.js
  src/ui/widget-forms/contents-filter/ContentsFilterBrowser.js
  src/ui/widget-forms/contents-filter/ContentsFilterBrowserContainer.js
  src/ui/widget-forms/contents-filter/ContentsFilterTable.js
Labels: approved, size/XXL

#367 ENG-2083 make page required if any link descr is filled
  src/ui/widget-forms/ContentsQueryConfig.js
  src/ui/widget-forms/ContentsQueryConfigContainer.js
Labels: approved, size/S
