Repository entando/entando-cms, pull requests merged in 2021-04, with the labels that each got.

#368 ENG-2184 Fix content active tab on search
  package-lock.json
  package.json
  src/state/contents/__tests__/reducer.test.js
  src/state/contents/reducer.js
Labels: approved, size/XL

#369 ENG-2266 make "categories" column in asset table shows...
  src/ui/assets/AssetsList.js
Labels: approved, size/XS

#370 ENG-2185 Fix content tab switch resetting search results
  src/state/contents/actions.js
Labels: approved, size/XS

#371 ENG-2246 implement searchable/indexable functionality for nested attribute under monolist
  src/state/content-type/__tests__/actions.test.js
  src/state/content-type/__tests__/reducer.test.js
  src/state/content-type/__tests__/selectors.test.js
  src/state/content-type/actions.js
  src/state/content-type/reducer.js
  src/state/content-type/selectors.js
  src/state/content-type/types.js
  src/ui/common/form/ContentTypeMonolistAttributeForm.js
  src/ui/content-type/attributes/monolist/MonolistAttributeFormContainer.js
Labels: approved, size/L

#373 ENG-2270 - content template form - content type field "null" resolved
  src/state/content-template/actions.js
  src/ui/content-template/AddContentTemplateFormContainer.js
  src/ui/content-template/EditContentTemplateFormContainer.js
  src/ui/content-template/__tests__/EditContentTemplateFormContainer.test.js
Labels: approved, size/M

#375 ENG-2194 open Info section on edit and ENG-2195 fix onclick if disabled
  src/ui/common/StickySave.js
  src/ui/edit-content/EditContentForm.js
Labels: approved, size/S

#377 Update package.json
  package.json
Labels: approved, size/XS

#376 ENG-2195 skip validation if link is not present and it's not required
  src/helpers/__tests__/attrValidation.test.js
  src/helpers/attrValidation.js
Labels: approved, size/S

#381 ENG-2302 resolve issue on removing active filter tag above asset list
  src/ui/assets/AssetsListContainer.js
  src/ui/categories/filter/CategoryTreeFilterContainer.js
  src/ui/categories/filter/CategoryTypeaheadFilter.js
Labels: approved, size/S

#379 ENG-2277 Fix fetching of published contents
  package-lock.json
  src/state/contents/actions.js
Labels: approved, size/S

#382 ENG-2240 add new list param to get contents api
  src/api/__tests__/contents.test.js
  src/api/contents.js
Labels: approved, size/XS
